# Generated by Django 5.0.6 on 2025-12-01 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('WAITING', 'Esperando'), ('PLAYING', 'Jugando'), ('FINISHED', 'Finalizado')], default='WAITING', max_length=20)),
                ('balotas_sorteadas', models.TextField(default='[]')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='editor.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartones', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartones', to='editor.partida')),
            ],
        ),
    ]
